CREATE TABLE IF NOT EXISTS `users`(
  `seq` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `level` INTEGER NOT NULL,
  `nickname` VARCHAR(64) NOT NULL,
  `extras` TEXT
) DEFAULT CHARACTER SET=utf8mb4;