# Runtime-variant configurations
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/springboot_mariadb?useUnicode=yes&characterEncoding=UTF-8
    username: francescojo
    password:

logging:
  level:
    org.springframework.web: DEBUG
    com.github.francescojo: DEBUG
