# Configuration template file for integration test.
# Don't put sensitive information like passwords into source code control!
server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: springboot-multimodule-kotlin
  profiles:
    # Empty if 'default'.
    active:
  datasource:
    # Automatic database initialisation. Maybe conflict to hibernate.
    # https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html
    initialization-mode: NEVER
    schema:
    data:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    username:
    password:
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      # Better to use create-drop for integration tests
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: false

management:
  server:
    add-application-context-header: false

logging:
  path:
  file:
  level:
    # Better to raise over than INFO in production environment
    org.springframework.web: INFO
    # All logs are handled and logged by com.github.fj.restapi.endpoint.CustomErrorHandler
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: OFF
    org.hibernate: INFO
    com.github.fj: DEBUG

app:
  push:
    fcm-private-key-location:
    fcm-server-key:
    fcm-project-id:
